version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/sportshub_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - AWS_REGION=auto
      - CLOUDFLARE_ACCOUNT_ID=123
      - CLOUDFLARE_ACCESS_KEY_ID=123
      - CLOUDFLARE_SECRET_ACCESS_KEY=123
      - CLOUDFLARE_BUCKET_NAME=123
    depends_on:
      - mysql
    networks:
      - sportshub-network

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sportshub_db
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - sportshub-network

networks:
  sportshub-network:
    driver: bridge

volumes:
  mysql-data:
